"""Hybrid Column Mapping Auto-Suggester.

Task: S2-AI-02
Implements a two-tier hybrid recommendation engine:
- Tier 1: Rapid fuzzy string similarity via rapidfuzz matching raw headers
  against canonical dictionary keys, display names, and industry synonyms.
- Tier 2: LLM fallback via PlantIQ BaseProvider for low-confidence (< threshold)
  or ambiguous/multilingual headers with sample value context.
"""

from __future__ import annotations

import asyncio
from dataclasses import asdict, dataclass, field
import json
from pathlib import Path
import re
import sys
import time
from typing import (
    Any,
    Coroutine,
    Dict,
    List,
    Literal,
    Optional,
    Sequence,
    Tuple,
    TypeVar,
    Union,
    cast,
)

_T = TypeVar("_T")

# Ensure project root is in sys.path
_project_root = str(Path(__file__).resolve().parent.parent.parent)
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from rapidfuzz import fuzz

from app.llm.base import BaseProvider
from app.llm.factory import get_llm_provider
from app.llm.types import Message, ProviderResponse

# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

MappingSource = Literal["exact", "fuzzy", "llm", "unmapped"]


@dataclass(frozen=True)
class MappingSuggestion:
    """Individual column mapping recommendation with confidence score."""

    raw_header: str
    suggested_canonical_key: Optional[str]
    confidence_score: float  # Normalized 0.0 to 1.0
    source: MappingSource
    reasoning: Optional[str] = None
    alternative_candidates: List[Tuple[str, float]] = field(default_factory=list)

    @property
    def is_mapped(self) -> bool:
        """Return True if a canonical key was successfully assigned."""
        return self.suggested_canonical_key is not None

    def to_dict(self) -> Dict[str, Any]:
        """Convert suggestion to JSON-serializable dictionary."""
        return asdict(self)


@dataclass(frozen=True)
class BatchMappingResult:
    """Batch mapping evaluation across all headers of a dataset."""

    suggestions: List[MappingSuggestion]
    total_columns: int
    fuzzy_matches_count: int
    llm_fallbacks_count: int
    unmapped_count: int
    average_confidence: float
    duration_ms: float

    def to_dict(self) -> Dict[str, Any]:
        """Convert result to JSON-serializable dictionary."""
        return asdict(self)


# ---------------------------------------------------------------------------
# Canonical Signal Definitions & Domain Synonym Lexicon
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CanonicalSignalMeta:
    """Metadata specification for a canonical signal or dimension."""

    key: str
    display_name: str
    unit: str
    description: str
    synonyms: List[str]


CANONICAL_SIGNALS: Dict[str, CanonicalSignalMeta] = {
    # Power
    "power_ac": CanonicalSignalMeta(
        key="power_ac",
        display_name="AC Active Power",
        unit="W",
        description="Inverter AC active power output delivered to the grid or load.",
        synonyms=[
            "ac power", "pac", "p ac", "active power", "grid power", "inv power",
            "power ac", "ac_power", "ac power kw", "p_ac_kw", "inverter_ac_power",
            "ac active power", "output power", "inv_pwr", "pac_kw", "p_ac",
            "inverter active power", "inverter power", "ac power w", "p grid",
        ],
    ),
    "power_dc": CanonicalSignalMeta(
        key="power_dc",
        display_name="DC Active Power",
        unit="W",
        description="DC power generated by the solar PV arrays before inverter conversion.",
        synonyms=[
            "dc power", "pdc", "p dc", "array power", "pv power", "power dc",
            "dc_power", "dc power kw", "p_dc_kw", "pv_power_kw", "input power",
            "dc active power", "array_pwr", "pdc_kw", "p_dc", "pv power w",
            "string power", "mppt power",
        ],
    ),
    # Energy
    "energy_ac_daily": CanonicalSignalMeta(
        key="energy_ac_daily",
        display_name="Daily AC Energy",
        unit="Wh",
        description="Cumulative AC energy generation for current day, resetting at midnight.",
        synonyms=[
            "daily yield", "daily energy", "e daily", "today energy",
            "daily generation", "day kwh", "yield daily", "e_heute", "energy today",
            "daily gen", "e_today", "day_yield", "daily_wh", "e_daily_kwh",
            "daily yield kwh", "etoday", "today generation", "day energy",
            "e today kwh", "e_today_kwh", "today kwh",
        ],
    ),
    "energy_ac_total": CanonicalSignalMeta(
        key="energy_ac_total",
        display_name="Total Lifetime AC Energy",
        unit="Wh",
        description="Cumulative lifetime AC generation register since commissioning.",
        synonyms=[
            "total yield", "total energy", "e total", "lifetime energy",
            "total generation", "tot kwh", "cumulative energy", "e_total",
            "total gen", "lifetime kwh", "tot_yield", "total_wh", "yield total",
            "etotal", "total kwh", "lifetime generation", "accumulated energy",
            "e total kwh", "e_total_kwh", "total mwh", "e_total_mwh",
        ],
    ),
    # Irradiance
    "irradiance_poa": CanonicalSignalMeta(
        key="irradiance_poa",
        display_name="Plane of Array Irradiance",
        unit="W/mÂ²",
        description="Solar irradiance incident upon the tilted PV collector plane.",
        synonyms=[
            "irradiation", "irradiance", "poa", "g poa", "solar radiation",
            "slrw avg", "pyranometer", "poa irradiance", "sun radiation",
            "w_strahlung", "radiation", "solar_rad", "sun_rad", "poa_irr",
            "g_poa_wm2", "solar poa", "plane of array", "g_poa", "solar irradiance",
            "irradiation kwm2", "irradiance wm2",
        ],
    ),
    "irradiance_ghi": CanonicalSignalMeta(
        key="irradiance_ghi",
        display_name="Global Horizontal Irradiance",
        unit="W/mÂ²",
        description="Solar irradiance received on a horizontal surface at ground level.",
        synonyms=[
            "ghi", "g ghi", "global horizontal irradiance", "horizontal irradiance",
            "ghi irradiance", "g_ghi", "horizontal radiation", "global irradiance",
        ],
    ),
    # Temperatures
    "temperature_ambient": CanonicalSignalMeta(
        key="temperature_ambient",
        display_name="Ambient Air Temperature",
        unit="Â°C",
        description="Outdoor ambient dry-bulb air temperature at the weather station.",
        synonyms=[
            "ambient temperature", "amb temp", "airtc avg", "t amb", "air temp",
            "outdoor temp", "air_temperature", "amb_temperature", "t_amb_c",
            "temp_amb", "ambient_temp", "ambient c", "t_amb", "air temperature c",
            "outdoor temperature",
        ],
    ),
    "temperature_module": CanonicalSignalMeta(
        key="temperature_module",
        display_name="PV Module Temperature",
        unit="Â°C",
        description="Surface temperature of the solar photovoltaic panel or cells.",
        synonyms=[
            "module temperature", "mod temp", "moduletc avg", "t mod",
            "cell temp", "panel temp", "module_temp", "pv_temp",
            "cell_temperature", "panel_temperature", "t_mod_c", "temp_module",
            "modeltemp", "t_mod", "module temp c", "panel temperature c",
            "surface temp", "back of module temp",
        ],
    ),
    # Electrical (Voltages, Currents, Frequency, PF)
    "voltage_dc": CanonicalSignalMeta(
        key="voltage_dc",
        display_name="DC Array Voltage",
        unit="V",
        description="DC input voltage from photovoltaic strings.",
        synonyms=[
            "dc voltage", "vdc", "v dc", "array voltage", "pv voltage",
            "u_dc", "udc", "pv1_voltage", "string voltage", "mppt voltage", "v_dc",
        ],
    ),
    "current_dc": CanonicalSignalMeta(
        key="current_dc",
        display_name="DC Array Current",
        unit="A",
        description="DC input current from photovoltaic strings.",
        synonyms=[
            "dc current", "idc", "i dc", "array current", "pv current",
            "i_dc", "pv1_current", "string current", "strom_dc", "mppt current",
        ],
    ),
    "voltage_ac": CanonicalSignalMeta(
        key="voltage_ac",
        display_name="AC Grid Voltage",
        unit="V",
        description="Inverter AC output voltage measured at the grid terminal.",
        synonyms=[
            "ac voltage", "vac", "v ac", "grid voltage", "u_ac", "uac",
            "line voltage", "phase voltage", "v_ac", "inverter voltage",
        ],
    ),
    "current_ac": CanonicalSignalMeta(
        key="current_ac",
        display_name="AC Grid Current",
        unit="A",
        description="Inverter AC output current injected into the grid.",
        synonyms=[
            "ac current", "iac", "i ac", "grid current", "i_ac",
            "inverter current", "strom_ac",
        ],
    ),
    "frequency_grid": CanonicalSignalMeta(
        key="frequency_grid",
        display_name="Grid Frequency",
        unit="Hz",
        description="AC utility grid frequency.",
        synonyms=[
            "grid frequency", "frequency", "grid freq", "freq", "f_grid",
            "ac frequency", "hz", "line frequency",
        ],
    ),
    "power_factor": CanonicalSignalMeta(
        key="power_factor",
        display_name="Power Factor",
        unit="dimensionless",
        description="Ratio of real active power to apparent power (cos phi).",
        synonyms=["power factor", "cosphi", "cos phi", "pf", "cos_phi"],
    ),
    # Weather & Environmental
    "wind_speed": CanonicalSignalMeta(
        key="wind_speed",
        display_name="Wind Speed",
        unit="m/s",
        description="Horizontal wind speed measured by anemometer.",
        synonyms=[
            "wind speed", "ws ms avg", "wind_velocity", "wind_speed_ms",
            "anemometer", "wind speed m s", "wind_spd",
        ],
    ),
    "wind_direction": CanonicalSignalMeta(
        key="wind_direction",
        display_name="Wind Direction",
        unit="deg",
        description="Compass direction from which the wind is blowing.",
        synonyms=["wind direction", "winddir", "wind_dir", "wind_deg", "vane"],
    ),
    # Relational Dimensions
    "timestamp": CanonicalSignalMeta(
        key="timestamp",
        display_name="Observation Timestamp",
        unit="ISO-8601",
        description="Chronological observation or logging timestamp dimension.",
        synonyms=[
            "date time", "datetime", "timestamp", "time", "date", "ts",
            "datum", "zeit", "recorded at", "created at", "time_stamp",
            "datetime_utc", "date_time", "utc_time", "record_time",
            "record time", "recordtime", "log_time", "sample_time",
        ],
    ),
    "device_id": CanonicalSignalMeta(
        key="device_id",
        display_name="Device / Inverter ID",
        unit="identifier",
        description="Unique hardware, inverter, or sensor string identifier.",
        synonyms=[
            "source key", "inverter id", "device id", "inv id", "serial number",
            "sourcekey", "inverter_name", "device_name", "logger id", "sensor id",
            "inv_name", "serial", "equipment_id", "station id", "station_id",
            "station", "logger_id", "sensor_id",
        ],
    ),
    "plant_id": CanonicalSignalMeta(
        key="plant_id",
        display_name="Plant ID",
        unit="identifier",
        description="Solar power plant or solar park organizational identifier.",
        synonyms=[
            "plant id", "plant", "site id", "park id",
            "plant_name", "solar_plant_id", "site_name", "project_id",
            "solar_park", "solar_farm", "farm_id", "facility_id",
        ],
    ),
}


# ---------------------------------------------------------------------------
# Header Normalization Helper
# ---------------------------------------------------------------------------


def normalize_header_text(header: str) -> str:
    """Normalize header string: split camelCase and replace delimiters with spaces."""
    # Split camelCase: e.g. "activePower" -> "active Power"
    s = re.sub(r"([a-z])([A-Z])", r"\1 \2", header)
    # Replace symbols and delimiters with space
    s = re.sub(r"[\s_\-\.\/:\(\)\[\]\^]+", " ", s)
    return s.strip().lower()


# ---------------------------------------------------------------------------
# Hybrid Mapping Suggester Engine
# ---------------------------------------------------------------------------


class MappingSuggester:
    """Two-tier hybrid column mapping suggestion engine."""

    def __init__(
        self,
        provider: Optional[BaseProvider] = None,
        default_threshold: float = 0.80,
        enable_llm_fallback: bool = True,
        llm_provider: Optional[BaseProvider] = None,
        fuzzy_threshold: Optional[float] = None,
    ) -> None:
        """Initialize suggester with an optional LLM provider for Tier 2 fallback."""
        self._provider = provider if provider is not None else llm_provider
        self.default_threshold = (
            fuzzy_threshold if fuzzy_threshold is not None else default_threshold
        )
        self.enable_llm_fallback = enable_llm_fallback

    def _get_provider(self) -> Optional[BaseProvider]:
        """Lazy load or return configured LLM provider if fallback is enabled."""
        if not self.enable_llm_fallback:
            return None
        if self._provider is not None:
            return self._provider
        try:
            self._provider = get_llm_provider()
            return self._provider
        except Exception:
            # If no provider can be initialized (e.g. offline without API key), provider remains None
            return None

    def _run_sync(self, coro: Coroutine[Any, Any, _T]) -> _T:
        """Run an async coroutine synchronously, safe in active or inactive event loops."""
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop is not None and loop.is_running():
            import concurrent.futures

            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                return pool.submit(asyncio.run, coro).result()
        else:
            return asyncio.run(coro)

    def suggest_header(
        self,
        raw_header: str,
        sample_values: Optional[List[Any]] = None,
        threshold: Optional[float] = None,
    ) -> MappingSuggestion:
        """Synchronously suggest canonical mapping for a single header (Tier 1 -> Tier 2 sync fallback)."""
        active_threshold = threshold if threshold is not None else self.default_threshold
        norm_header = normalize_header_text(raw_header)

        # Empty or non-alphanumeric header check
        if not norm_header:
            return MappingSuggestion(
                raw_header=raw_header,
                suggested_canonical_key=None,
                confidence_score=0.0,
                source="unmapped",
                reasoning=f"Header '{raw_header}' contains no alphanumeric tokens.",
            )

        # -------------------------------------------------------------------
        # Fast Path: Exact Match against key or synonyms
        # -------------------------------------------------------------------
        for key, meta in CANONICAL_SIGNALS.items():
            if norm_header == normalize_header_text(key):
                return MappingSuggestion(
                    raw_header=raw_header,
                    suggested_canonical_key=key,
                    confidence_score=1.0,
                    source="exact",
                    reasoning=f"Exact match with canonical key '{key}'.",
                )
            for syn in meta.synonyms:
                if norm_header == normalize_header_text(syn):
                    return MappingSuggestion(
                        raw_header=raw_header,
                        suggested_canonical_key=key,
                        confidence_score=1.0,
                        source="exact",
                        reasoning=f"Exact match with domain synonym '{syn}' for '{key}'.",
                    )

        # -------------------------------------------------------------------
        # Tier 1: Fuzzy String Similarity via rapidfuzz
        # -------------------------------------------------------------------
        candidates_scores: List[Tuple[str, float]] = []

        for key, meta in CANONICAL_SIGNALS.items():
            best_score = 0.0
            # Test against key itself
            key_norm = normalize_header_text(key)
            score_key = max(
                fuzz.token_sort_ratio(norm_header, key_norm),
                fuzz.ratio(norm_header, key_norm),
                fuzz.partial_ratio(norm_header, key_norm) * 0.90,
            )
            best_score = max(best_score, score_key)

            # Test against synonyms
            for syn in meta.synonyms:
                syn_norm = normalize_header_text(syn)
                score_syn = max(
                    fuzz.token_sort_ratio(norm_header, syn_norm),
                    fuzz.ratio(norm_header, syn_norm),
                )
                best_score = max(best_score, score_syn)

            normalized_score = round(best_score / 100.0, 3)
            candidates_scores.append((key, normalized_score))

        # Sort candidates descending by score
        candidates_scores.sort(key=lambda x: x[1], reverse=True)
        top_key, top_score = candidates_scores[0]
        alternatives = candidates_scores[1:4]

        # If fuzzy match is confident (>= threshold), return Tier 1 suggestion
        if top_score >= active_threshold:
            return MappingSuggestion(
                raw_header=raw_header,
                suggested_canonical_key=top_key,
                confidence_score=top_score,
                source="fuzzy",
                reasoning=f"High-confidence fuzzy string match ({top_score:.1%}) with '{top_key}'.",
                alternative_candidates=alternatives,
            )

        # -------------------------------------------------------------------
        # Tier 2: LLM Fallback (Sync runner)
        # -------------------------------------------------------------------
        provider = self._get_provider()
        if provider is not None:
            try:
                llm_suggestion = self._run_sync(
                    self._query_llm_fallback(
                        raw_header=raw_header,
                        sample_values=sample_values,
                        top_candidates=candidates_scores[:4],
                    )
                )
                if llm_suggestion:
                    return llm_suggestion
            except Exception:
                pass  # Fall through to unmapped if LLM fails

        # Fallback when LLM not available or cannot deduce mapping
        return MappingSuggestion(
            raw_header=raw_header,
            suggested_canonical_key=None,
            confidence_score=top_score,
            source="unmapped",
            reasoning=f"Header '{raw_header}' could not be reliably mapped to any canonical signal.",
            alternative_candidates=alternatives,
        )

    async def suggest_header_async(
        self,
        raw_header: str,
        sample_values: Optional[List[Any]] = None,
        threshold: Optional[float] = None,
    ) -> MappingSuggestion:
        """Asynchronously suggest canonical mapping for a single header."""
        active_threshold = threshold if threshold is not None else self.default_threshold
        norm_header = normalize_header_text(raw_header)

        # Empty or non-alphanumeric header check
        if not norm_header:
            return MappingSuggestion(
                raw_header=raw_header,
                suggested_canonical_key=None,
                confidence_score=0.0,
                source="unmapped",
                reasoning=f"Header '{raw_header}' contains no alphanumeric tokens.",
            )

        # 1. Fast Path
        for key, meta in CANONICAL_SIGNALS.items():
            if norm_header == normalize_header_text(key):
                return MappingSuggestion(
                    raw_header=raw_header,
                    suggested_canonical_key=key,
                    confidence_score=1.0,
                    source="exact",
                    reasoning=f"Exact match with canonical key '{key}'.",
                )
            for syn in meta.synonyms:
                if norm_header == normalize_header_text(syn):
                    return MappingSuggestion(
                        raw_header=raw_header,
                        suggested_canonical_key=key,
                        confidence_score=1.0,
                        source="exact",
                        reasoning=f"Exact match with domain synonym '{syn}' for '{key}'.",
                    )

        # 2. Tier 1 Fuzzy Match
        candidates_scores: List[Tuple[str, float]] = []
        for key, meta in CANONICAL_SIGNALS.items():
            best_score = 0.0
            key_norm = normalize_header_text(key)
            score_key = max(
                fuzz.token_sort_ratio(norm_header, key_norm),
                fuzz.ratio(norm_header, key_norm),
                fuzz.partial_ratio(norm_header, key_norm) * 0.90,
            )
            best_score = max(best_score, score_key)

            for syn in meta.synonyms:
                syn_norm = normalize_header_text(syn)
                score_syn = max(
                    fuzz.token_sort_ratio(norm_header, syn_norm),
                    fuzz.ratio(norm_header, syn_norm),
                )
                best_score = max(best_score, score_syn)

            normalized_score = round(best_score / 100.0, 3)
            candidates_scores.append((key, normalized_score))

        candidates_scores.sort(key=lambda x: x[1], reverse=True)
        top_key, top_score = candidates_scores[0]
        alternatives = candidates_scores[1:4]

        if top_score >= active_threshold:
            return MappingSuggestion(
                raw_header=raw_header,
                suggested_canonical_key=top_key,
                confidence_score=top_score,
                source="fuzzy",
                reasoning=f"High-confidence fuzzy string match ({top_score:.1%}) with '{top_key}'.",
                alternative_candidates=alternatives,
            )

        # 3. Tier 2 LLM Fallback
        provider = self._get_provider()
        if provider is not None:
            llm_suggestion = await self._query_llm_fallback(
                raw_header=raw_header,
                sample_values=sample_values,
                top_candidates=candidates_scores[:4],
            )
            if llm_suggestion:
                return llm_suggestion

        # Fallback when LLM not available or cannot deduce mapping
        return MappingSuggestion(
            raw_header=raw_header,
            suggested_canonical_key=None,
            confidence_score=top_score,
            source="unmapped",
            reasoning=f"Header '{raw_header}' could not be reliably mapped to any canonical signal.",
            alternative_candidates=alternatives,
        )

    def suggest_batch(
        self,
        headers: Sequence[str],
        sample_data: Optional[Dict[str, List[Any]]] = None,
        threshold: Optional[float] = None,
    ) -> BatchMappingResult:
        """Synchronously suggest mappings for a list of column headers."""
        start_time = time.perf_counter()
        suggestions: List[MappingSuggestion] = []

        for h in headers:
            samples = sample_data.get(h) if sample_data else None
            sug = self.suggest_header(h, sample_values=samples, threshold=threshold)
            suggestions.append(sug)

        return self._build_batch_result(suggestions, start_time)

    async def suggest_batch_async(
        self,
        headers: Sequence[str],
        sample_data: Optional[Dict[str, List[Any]]] = None,
        threshold: Optional[float] = None,
    ) -> BatchMappingResult:
        """Asynchronously suggest mappings for a list of column headers concurrently."""
        start_time = time.perf_counter()
        tasks = []

        for h in headers:
            samples = sample_data.get(h) if sample_data else None
            tasks.append(self.suggest_header_async(h, sample_values=samples, threshold=threshold))

        suggestions: List[MappingSuggestion] = await asyncio.gather(*tasks)
        return self._build_batch_result(suggestions, start_time)

    def _build_batch_result(
        self, suggestions: List[MappingSuggestion], start_time: float
    ) -> BatchMappingResult:
        """Aggregate suggestions list into BatchMappingResult summary."""
        duration_ms = (time.perf_counter() - start_time) * 1000.0
        fuzzy_count = sum(1 for s in suggestions if s.source in ("exact", "fuzzy"))
        llm_count = sum(1 for s in suggestions if s.source == "llm")
        unmapped_count = sum(1 for s in suggestions if s.source == "unmapped" or s.suggested_canonical_key is None)
        avg_conf = (
            sum(s.confidence_score for s in suggestions) / len(suggestions)
            if suggestions
            else 0.0
        )

        return BatchMappingResult(
            suggestions=suggestions,
            total_columns=len(suggestions),
            fuzzy_matches_count=fuzzy_count,
            llm_fallbacks_count=llm_count,
            unmapped_count=unmapped_count,
            average_confidence=round(avg_conf, 3),
            duration_ms=round(duration_ms, 2),
        )

    # Convenience method aliases
    suggest = suggest_header
    suggest_async = suggest_header_async

    # -----------------------------------------------------------------------
    # Tier 2 LLM Prompting & Execution
    # -----------------------------------------------------------------------

    async def _query_llm_fallback(
        self,
        raw_header: str,
        sample_values: Optional[List[Any]],
        top_candidates: List[Tuple[str, float]],
    ) -> Optional[MappingSuggestion]:
        """Construct targeted prompt and deduce canonical key via LLM provider."""
        provider = self._get_provider()
        if not provider:
            return None

        # Build concise catalog of canonical signals
        catalog_lines = [
            f"- {k}: {m.display_name} ({m.unit}) â€” {m.description}"
            for k, m in CANONICAL_SIGNALS.items()
        ]
        catalog_str = "\n".join(catalog_lines)

        system_prompt = (
            "You are an expert Solar PV SCADA Data Engineer for PlantIQ.\n"
            "Your objective is to map an ambiguous, abbreviated, or foreign telemetry header to our canonical signal dictionary.\n"
            "Here is the authoritative catalog of canonical keys:\n"
            f"{catalog_str}\n\n"
            "Strict Output Format: Respond ONLY with a valid JSON object matching this schema:\n"
            "{\n"
            '  "suggested_canonical_key": "<canonical_key_or_null>",\n'
            '  "confidence_score": <float between 0.0 and 1.0>,\n'
            '  "reasoning": "<concise explanation>"\n'
            "}\n"
            "If the column is unrelated to solar telemetry or cannot be mapped, set suggested_canonical_key to null."
        )

        sample_str = f"Sample values: {sample_values[:5]}" if sample_values else "Sample values: None available"
        candidates_str = ", ".join(f"{c[0]} ({c[1]:.1%})" for c in top_candidates)

        user_content = (
            f"Header to map: '{raw_header}'\n"
            f"{sample_str}\n"
            f"Top fuzzy heuristic candidates: {candidates_str}\n\n"
            "Deduce the correct canonical key."
        )

        try:
            response: ProviderResponse = await provider.chat(
                messages=[Message(role="user", content=user_content)],
                system=system_prompt,
                temperature=0.0,
                timeout=15.0,
            )

            raw_text = response.text.strip()
            # Extract JSON from response block
            match = re.search(r"\{.*\}", raw_text, re.DOTALL)
            if not match:
                return None

            payload = json.loads(match.group(0))
            suggested_key = payload.get("suggested_canonical_key")
            conf = float(payload.get("confidence_score", 0.70))
            reasoning = payload.get("reasoning", "Deducted via LLM semantic analysis.")

            # Validate that suggested key is an active canonical signal
            if suggested_key and suggested_key in CANONICAL_SIGNALS:
                return MappingSuggestion(
                    raw_header=raw_header,
                    suggested_canonical_key=suggested_key,
                    confidence_score=round(conf, 3),
                    source="llm",
                    reasoning=f"LLM Fallback: {reasoning}",
                    alternative_candidates=top_candidates,
                )
            elif suggested_key is None:
                return MappingSuggestion(
                    raw_header=raw_header,
                    suggested_canonical_key=None,
                    confidence_score=round(conf, 3),
                    source="unmapped",
                    reasoning=f"LLM Classification: {reasoning}",
                    alternative_candidates=top_candidates,
                )
        except Exception:
            return None

        return None


# ---------------------------------------------------------------------------
# Convenience Module API
# ---------------------------------------------------------------------------


def suggest_mappings(
    headers: Sequence[str],
    sample_data: Optional[Dict[str, List[Any]]] = None,
    threshold: float = 0.80,
    provider: Optional[BaseProvider] = None,
) -> BatchMappingResult:
    """Convenience functional wrapper to suggest column mappings for a dataset."""
    suggester = MappingSuggester(provider=provider, default_threshold=threshold)
    return suggester.suggest_batch(headers, sample_data=sample_data, threshold=threshold)


async def suggest_mappings_async(
    headers: Sequence[str],
    sample_data: Optional[Dict[str, List[Any]]] = None,
    threshold: float = 0.80,
    provider: Optional[BaseProvider] = None,
) -> BatchMappingResult:
    """Asynchronous convenience functional wrapper to suggest column mappings."""
    suggester = MappingSuggester(provider=provider, default_threshold=threshold)
    return await suggester.suggest_batch_async(headers, sample_data=sample_data, threshold=threshold)

