from app.db.database import SessionLocal
from app.models import CanonicalSignal


signals = [
    {
        "key": "power_ac",
        "name": "AC Power",
        "category": "power",
        "unit": "kW",
        "y_min": 0,
        "y_max": None,
        "applicable_types": ["solar", "wind", "process"],
        "description": "Active AC power output.",
    },
    {
        "key": "power_dc",
        "name": "DC Power",
        "category": "power",
        "unit": "kW",
        "y_min": 0,
        "y_max": None,
        "applicable_types": ["solar"],
        "description": "DC power generated by the solar plant.",
    },
    {
        "key": "energy",
        "name": "Energy",
        "category": "energy",
        "unit": "kWh",
        "y_min": 0,
        "y_max": None,
        "applicable_types": ["solar", "wind", "process"],
        "description": "Energy generated during the measurement interval.",
    },
    {
        "key": "irradiance",
        "name": "Irradiance",
        "category": "weather",
        "unit": "W/m2",
        "y_min": 0,
        "y_max": None,
        "applicable_types": ["solar"],
        "description": "Solar irradiance measured at the plant.",
    },
    {
        "key": "module_temperature",
        "name": "Module Temperature",
        "category": "weather",
        "unit": "degC",
        "y_min": -40,
        "y_max": 100,
        "applicable_types": ["solar"],
        "description": "Solar module temperature.",
    },
    {
        "key": "ambient_temperature",
        "name": "Ambient Temperature",
        "category": "weather",
        "unit": "degC",
        "y_min": -50,
        "y_max": 80,
        "applicable_types": ["solar", "wind", "process"],
        "description": "Ambient air temperature.",
    },
    {
        "key": "wind_speed",
        "name": "Wind Speed",
        "category": "weather",
        "unit": "m/s",
        "y_min": 0,
        "y_max": None,
        "applicable_types": ["wind"],
        "description": "Measured wind speed.",
    },
    {
        "key": "wind_direction",
        "name": "Wind Direction",
        "category": "weather",
        "unit": "deg",
        "y_min": 0,
        "y_max": 360,
        "applicable_types": ["wind"],
        "description": "Measured wind direction.",
    },
    {
        "key": "voltage",
        "name": "Voltage",
        "category": "electrical",
        "unit": "V",
        "y_min": 0,
        "y_max": None,
        "applicable_types": ["solar", "wind", "process"],
        "description": "Electrical voltage measurement.",
    },
    {
        "key": "current",
        "name": "Current",
        "category": "electrical",
        "unit": "A",
        "y_min": 0,
        "y_max": None,
        "applicable_types": ["solar", "wind", "process"],
        "description": "Electrical current measurement.",
    },
]


def seed_signals():
    db = SessionLocal()

    try:
        for signal_data in signals:
            existing = db.get(
                CanonicalSignal,
                signal_data["key"],
            )

            if existing:
                print(f"Already exists: {signal_data['key']}")
                continue

            signal = CanonicalSignal(**signal_data)
            db.add(signal)

        db.commit()

        print("Canonical signals seeded successfully.")

    finally:
        db.close()


if __name__ == "__main__":
    seed_signals()
